/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppCakeRouteImport } from './routes/app/cake'
import { Route as AppCartRouteImport } from './routes/app/cart'
import { Route as AppCheckoutRouteImport } from './routes/app/checkout'
import { Route as AppFoodRouteImport } from './routes/app/food'
import { Route as AppManageRouteImport } from './routes/app/manage'
import { Route as AppMedicineRouteImport } from './routes/app/medicine'
import { Route as AppOrdersRouteImport } from './routes/app/orders'
import { Route as AppRSlugRouteImport } from './routes/app/r/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppCakeRoute = AppCakeRouteImport.update({
  id: '/cake',
  path: '/cake',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodRoute = AppFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => AppRoute,
} as any)
const AppManageRoute = AppManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicineRoute = AppMedicineRouteImport.update({
  id: '/medicine',
  path: '/medicine',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppRSlugRoute = AppRSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AppAccountRoute
  '/app/cake': typeof AppCakeRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/food': typeof AppFoodRoute
  '/app/manage': typeof AppManageRoute
  '/app/medicine': typeof AppMedicineRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/': typeof AppIndexRoute
  '/app/r/$slug': typeof AppRSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AppAccountRoute
  '/app/cake': typeof AppCakeRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/food': typeof AppFoodRoute
  '/app/manage': typeof AppManageRoute
  '/app/medicine': typeof AppMedicineRoute
  '/app/orders': typeof AppOrdersRoute
  '/app': typeof AppIndexRoute
  '/app/r/$slug': typeof AppRSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AppAccountRoute
  '/app/cake': typeof AppCakeRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/food': typeof AppFoodRoute
  '/app/manage': typeof AppManageRoute
  '/app/medicine': typeof AppMedicineRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/': typeof AppIndexRoute
  '/app/r/$slug': typeof AppRSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/app/account'
    | '/app/cake'
    | '/app/cart'
    | '/app/checkout'
    | '/app/food'
    | '/app/manage'
    | '/app/medicine'
    | '/app/orders'
    | '/app/'
    | '/app/r/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/app/account'
    | '/app/cake'
    | '/app/cart'
    | '/app/checkout'
    | '/app/food'
    | '/app/manage'
    | '/app/medicine'
    | '/app/orders'
    | '/app'
    | '/app/r/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/app/account'
    | '/app/cake'
    | '/app/cart'
    | '/app/checkout'
    | '/app/food'
    | '/app/manage'
    | '/app/medicine'
    | '/app/orders'
    | '/app/'
    | '/app/r/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cake': {
      id: '/app/cake'
      path: '/cake'
      fullPath: '/app/cake'
      preLoaderRoute: typeof AppCakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cart': {
      id: '/app/cart'
      path: '/cart'
      fullPath: '/app/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/food': {
      id: '/app/food'
      path: '/food'
      fullPath: '/app/food'
      preLoaderRoute: typeof AppFoodRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manage': {
      id: '/app/manage'
      path: '/manage'
      fullPath: '/app/manage'
      preLoaderRoute: typeof AppManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medicine': {
      id: '/app/medicine'
      path: '/medicine'
      fullPath: '/app/medicine'
      preLoaderRoute: typeof AppMedicineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/r/$slug': {
      id: '/app/r/$slug'
      path: '/r/$slug'
      fullPath: '/app/r/$slug'
      preLoaderRoute: typeof AppRSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCakeRoute: typeof AppCakeRoute
  AppCartRoute: typeof AppCartRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppFoodRoute: typeof AppFoodRoute
  AppManageRoute: typeof AppManageRoute
  AppMedicineRoute: typeof AppMedicineRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRSlugRoute: typeof AppRSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCakeRoute: AppCakeRoute,
  AppCartRoute: AppCartRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppFoodRoute: AppFoodRoute,
  AppManageRoute: AppManageRoute,
  AppMedicineRoute: AppMedicineRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppIndexRoute: AppIndexRoute,
  AppRSlugRoute: AppRSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
